# Generated by Django 2.0.3 on 2018-03-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('portada', models.FileField(default='img/disco.jpg', upload_to='portadas/')),
            ],
        ),
        migrations.CreateModel(
            name='Tiraera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trapero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aka', models.CharField(max_length=100)),
                ('nombre_real', models.CharField(blank=True, max_length=250, null=True)),
                ('ano_nacimiento', models.IntegerField(default=1980)),
                ('foto', models.FileField(default='logos/anonymous.jpg', upload_to='fotos/')),
            ],
        ),
        migrations.AddField(
            model_name='tiraera',
            name='trapero_recibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trapero_recibor', to='traperos.Trapero'),
        ),
        migrations.AddField(
            model_name='tiraera',
            name='trapero_tira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trapero_tirador', to='traperos.Trapero'),
        ),
        migrations.AddField(
            model_name='disco',
            name='trapero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disco_trapero', to='traperos.Trapero'),
        ),
    ]
