# Generated by Django 2.0.3 on 2018-04-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traperos', '0002_alerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='trapero',
        ),
        migrations.AddField(
            model_name='disco',
            name='trapero',
            field=models.ManyToManyField(related_name='disco_trapero', to='traperos.Trapero'),
        ),
        migrations.AlterField(
            model_name='tiraera',
            name='trapero_recibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trapero_recibidor', to='traperos.Trapero'),
        ),
    ]
