# Generated by Django 2.0.3 on 2018-03-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiraera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trapero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('aka', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tiraera',
            name='trapero_recibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trapero_recibor', to='traperos.Trapero'),
        ),
        migrations.AddField(
            model_name='tiraera',
            name='trapero_tira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trapero_tirador', to='traperos.Trapero'),
        ),
        migrations.AddField(
            model_name='disco',
            name='trapero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disco_trapero', to='traperos.Trapero'),
        ),
    ]
