# Generated by Django 2.0.3 on 2018-03-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traperos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='portada',
            field=models.FileField(default='logos/anonymous.jpg', upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='trapero',
            name='foto',
            field=models.FileField(default='logos/anonymous.jpg', upload_to='fotos/'),
        ),
    ]
