# Generated by Django 2.0.3 on 2018-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traperos', '0002_auto_20180320_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='portada',
            field=models.FileField(default='logos/disco_vacio.jpg', upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='trapero',
            name='apellidos',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trapero',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
